### ISSUE TITLE
1.1 migration /api/v1/status inconsistency

### ISSUE THREAD

**Issue by jebonfig** [hyperledger/firefly#1032]
I've attempted to upgrade my firefly instance from 1.0 to 1.1-rc using the migration guide

When starting up 1.1 for the first time, an API call to `/api/v1/status` shows my org is registered, but my node is not [see below for full response].  

I was expecting both the org and the node to be unregistered at this point in the migration, as the guide instructs us the org and node will need to be reregistered manually in a later step

However, a call to `/api/v1/network/organizations` returns `[]` which is in line with expectations

`/api/v1/status`
```
{
  "namespace": {
    "name": "default",
    "networkName": "default",
    "description": "",
    "created": "2022-08-31T19:30:38.411907442Z"
  },
  "node": {
    "name": "zzak1jp9qi",
    "registered": false
  },
  "org": {
    "name": "zzak1jp9qi",
    "registered": true,
    "did": "did:firefly:org/zzak1jp9qi",
    "id": "ecf12f34-f5a2-47d2-b81a-8b2897329a17",
    "verifiers": [
      {
        "type": "ethereum_address",
        "value": "0xa45436691a6574ca6c873578730af4f0a6e210ec"
      }
    ]
  },
  "plugins": {
    "blockchain": [
      {
        "name": "blockchain0",
        "pluginType": "ethereum"
      }
    ],
    "database": [
      {
        "name": "database0",
        "pluginType": "sqlite3"
      }
    ],
    "dataExchange": [
      {
        "name": "dataexchange0",
        "pluginType": "ffdx"
      }
    ],
    "events": [
      {
        "pluginType": "system"
      },
      {
        "pluginType": "websockets"
      },
      {
        "pluginType": "webhooks"
      }
    ],
    "identity": [],
    "sharedStorage": [
      {
        "name": "sharedstorage0",
        "pluginType": "ipfs"
      }
    ],
    "tokens": [
      {
        "name": "erc20_erc721",
        "pluginType": "fftokens"
      }
    ]
  },
  "multiparty": {
    "enabled": true,
    "contract": {
      "active": {
        "index": 0,
        "location": {
          "address": "0x359ce02812c4e08b492e7c2543216f98bfff7550"
        },
        "info": {
          "subscription": "sb-0319aaa9-9338-4901-5d12-543d0848d3a0",
          "version": 1
        }
      }
    }
  }
}
```

**Comment by awrichar** [comment]
The original fix (#1035) caused the org to appear _unregistered_ (along with the node) immediately after upgrading FireFly to 1.1 (while using a legacy environment whose orgs/nodes had been registered to ff_system). However, this renders the environment broken until re-registration, which is undesirable.

The new fix (#1048) reverts this and goes in the opposite direction - by causing the node to appear _registered_ in this situation (along with the org) if it was registered on ff_system. This will allow the system to continue function normally as long as it continues to use network rules V1. Re-registration can be performed at any point (but must be done before upgrading to a V2 contract).
