### ISSUE TITLE
Key '0xAAA...' has not been registered by any identity, and a separate 'author' was not supplied

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#1049]
When sending a POST to `/messages/private` using a resolved signing key, I get the following result:

Payload:

```json
{
  "header": {
    "tag": "TestingNewSigningKey",
    "key":"0x53b7680df9b0644e3bd6490a09ba07768839d47f"
  },
  "data": [
    {
      "value": "Data"
    }
  ]
}
```

Request:

```json
{
    "error": "FF10206: Invalid author specified: FF10356: Key '0x53b7680df9b0644e3bd6490a09ba07768839d47f' has not been registered by any identity, and a separate 'author' was not supplied"
}
```

**Comment by eberger727** [comment]
[chainwall.log](https://github.com/hyperledger/firefly/files/9514841/chainwall.log)

**Comment by eberger727** [comment]
[firefly.log](https://github.com/hyperledger/firefly/files/9515045/firefly.log)

**Comment by eberger727** [comment]
[evmconnect.log](https://github.com/hyperledger/firefly/files/9515516/evmconnect.log)

**Comment by awrichar** [comment]
I think this is behaving as designed. If you use a signing key that isn't registered to a FireFly identity, you have to also specify an "author" (in the form of a DID).

**Comment by eberger727** [comment]
Yes, @awrichar this is working as intended. Meant to close this earlier.
