### ISSUE TITLE
Should we introduce a GraphQL layer?

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#105]
@vipinsun made a great observation on a community call on 30th June, that there's a whole space of innovation (such as The Graph) that listen to events from a blockchain, and build a complete (or semi-complete) off-chain GraphQL queryable store of the on-chain information.

The unanswered questions on the call was:
- Is the state of the technology such that such a layer could be introduce into FireFly in a way that's practical, and can support multiple protocols?
- Should this be a plugin capability that's orthogonal to the fundamental constructs that FireFly models (like tokens), or should we consider such a layer as a base layer under that modelling?

**Comment by peterbroadhurst** [comment]
Vipin called out the value of GraphQL as a way to allow server-side aggregation of complex relationships, to avoid the amount of back-and-forth between the application and the server over the API.

I note the other approach, is to pre-perform this relationship mapping according to a well specified schema (such as modelling token relationships).

Clearly the latter is only possible when you do the modelling, and is thus less flexible.
The former can be used for any on-chain logic, but the amount of understanding needed from the developer for simple scenarios might be an order of magnitude larger.

**Comment by shorsher** [comment]
Closing this issue. Please open a [FIR](https://github.com/hyperledger/firefly-fir) for a proposal and further discussion.
