### ISSUE TITLE
UI Block Explorer in Dev env

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#108]
Currently you get a ganache CLI node, but there's no way to ask the CLI to use/create an existing Ganache UI node.
So if you want to see what's going on with the blockchain, it's a little hard - tailing logs.

Would be nice to have an option that lets you have a block explorer.

**Comment by nguyer** [comment]
@peterbroadhurst Great idea. I wonder if this should be a CLI issue though. Or do we want the block explorer integrated into FireFly itself? Right now FireFly (core) has no knowledge of Ganache directly.

**Comment by nguyer** [comment]
Is there another easy/good block explorer we could use besides Ganache? Unfortunately the Ganache GUI is not capable of connecting to a _different_ Ganache CLI. The UI always starts its own chain. There's an open issue that's been around for 3 years where people have been asking for this behavior: https://github.com/trufflesuite/ganache/issues/322 I'm guessing it may not be worth our time to try to tie in Ganache GUI at this point, unless Ganache itself is improved.

**Comment by peterbroadhurst** [comment]
There are lots of block explorers out there for sure (blockscout etc.) in various stages of openness and maturity.
There is just a bunch of complexity to many of them, to get them running.

One project that was very deliberately lightweight is: https://github.com/Alethio/ethereum-lite-explorer
However, I do not know the state of activity on that project today, or whether it has sufficient function to be useful (being able to decompose input payloads into JSON is a really important feature).

**Comment by peterbroadhurst** [comment]
... did just want to be clear on one part of my original assumption, that if it were Ganache based, we would run the full Ganache _instead_ of the CLI version (not alongside it).

**Comment by peterbroadhurst** [comment]
... I think for Ganache to be able to show you the inputs and outputs, it might be necessary to use the Truffle tooling to do the installation of the contract too, so that the Truffle suite integration between the two components would allow Ganache to know the ABI and show you the transaction input details.

**Comment by shorsher** [comment]
Closing this issue. Please submit a [FIR](https://github.com/hyperledger/firefly-fir) for proposals and further discussion
