### ISSUE TITLE
Blockchain invoke intermittently failing when using FireFly+ethconnect

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1083]
I'm running a 2-member stack with FireFly and ethconnect. I've deployed a custom smart contract and am using FireFly's "invoke" method to invoke methods on the contract from both members. Frequently I see these operations fail - it seems to generally be when both members are simultaneously invoking the contract.

[logs.tgz](https://github.com/hyperledger/firefly/files/9717607/logs.tgz)

**Comment by awrichar** [comment]
Operation `d4e63de2-89e0-4911-b40b-87ef1521bcdd` failed here on node0. This maps to transaction `0xdb52bdb6cb2fa547e0dc503c0bd61d3c5fc7b04a77856812ae2cf0d3bfb15875` on the blockchain.

**Comment by peterbroadhurst** [comment]
```
[2022-10-04T20:14:45.811Z] ERROR <-- POST / [400]: FFEC100178: Supplied 1 parameters for ABI that supports 0
```

**Comment by peterbroadhurst** [comment]
This looks like an out of gas condition - I suspect the TX used the full `40633` that came from the estimate.

The `ethconnect` code gives a 20% boost by default to the output of `eth_estimateGas`, but there are cases where this isn't enough buffer.

So you can increase the buffer with the following ethconnect tuning:

```
rest:
  rest-gateway:
    gasEstimationFactor: 2.0
```

e.g. you'd create a dev CLI chain with:

```
ff init --connector-config /tmp/give_it_more_gas.yaml dev 1
```
