### ISSUE TITLE
Filtering by topics with an `_` does not return correct results

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#1084]
Filtering the `/messages` endpoint with a topic that contains an `_` results in an empty array

To reproduce:

1. Send POST to `api/v1/broadcast` with the following payload:
```json
{
  "header": {
      "topics": ["test_1"]
  },
  "data": [
    {
      "value": "This is a broadcast"
    }
  ]
}
```

2. Try to fetch the message: http://localhost:5000/api/v1/namespaces/default/messages?topics=@test_1
3. You can see that the underscore is the issue, because http://localhost:5000/api/v1/namespaces/default/messages?topics=@test returns the message correctly

**Comment by awrichar** [comment]
See https://github.com/hyperledger/firefly-common/issues/83
