### ISSUE TITLE
Cannot filter contract listeners by name

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1102]
Seems to just be missing from the query factory on the GET API for contract listeners.

**Comment by erkanercan** [comment]
Just to be clear, you want to add a name field on ContractListenerQueryFactory at
 https://github.com/hyperledger/firefly/blob/0e6ae4642a3a4752a0d3ce097705351a75475ef3/pkg/database/plugin.go right? @awrichar 

If yes, I'll be providing a PR for this issue.
