### ISSUE TITLE
Failure to confirm broadcasts after receiving a broadcast without data

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly#1127]
If a firefly node sends a broadcast without any data, the rest of the network seems to get into a weird state.

My observations:
1. The sending node will have the broadcast show up as `confirmed`, but other nodes do not seem to receive the message. 
2. If other nodes send a broadcast, it will be stuck in `sent` and never reach confirmed.

Example request:
```
curl -X 'POST' \
  'http://127.0.0.1:5000/api/v1/messages/broadcast' \
  -H 'accept: application/json' \
  -H 'Request-Timeout: 2m0s' \
  -H 'Content-Type: application/json' \
  -d '{
  "header": {
    "tag": "TEST"
  }
}'
```

**Comment by awrichar** [comment]
Tried to reproduce. I saw the message get `confirmed` by the sender, but just never received by anyone else. The receiving node clearly discarded it:
```
[2023-01-26T18:23:32.805Z] ERROR Invalid batch '7f95a2cb-a752-4df6-bcdc-5949808789fd'. Missing messages (1) or data (0) dbtx=bJfwsnmG ns=default pid=1 role=event-manager
```

Biggest question is which is the correct behavior - don't allow sending an empty batch, or allow receiving an empty batch? It appears that we're inconsistent right now.
