### ISSUE TITLE
Mark ethconnect as deprecated, make evmconnect the default EVM connector

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/firefly#1135]
FireFly heavily encourages the use of evmconnect over ethconnect and in v1.2 the proposal is to mark ethconnect as deprecated and require `-c ethconnect` on the FireFly CLI if a user wishes to continue using it.

This will need documenting:

- https://hyperledger.github.io/firefly/architecture/blockchain_connector_framework.html 
- https://hyperledger.github.io/firefly/contributors/code_repositories.html
- https://hyperledger.github.io/firefly/releasenotes/

**Comment by nguyer** [comment]
It's probably worth a note in the CLI release notes, but I'm not sure that there's a big migration concern of just setting the CLI's default to `evmconnect`. It will only affect new, local development environments created with the FireFly CLI.

It's also worth double checking our CI scripts and E2E tests to make sure they don't rely on the implicit default of ethconnect. I don't think they do in most cases, but worth a double check anyway. I'll do that as part of the CLI change.

**Comment by matthew1001** [comment]
Yes I was thinking of user script migration for anyone relying on `ff init` without specifying -c and assuming they'll get `ethconnect`. Agreed that the CLI will need an update to its release notes. Do you want to raise an issue for the cli to track in the kanban?

**Comment by matthew1001** [comment]
We might want to update the plugin diagram to replace `ethconnect` in the connector layer with `evmconnect`? 

![Image](https://user-images.githubusercontent.com/6599269/211525085-ab8febaa-b046-473f-8da2-9727967b04f6.png)
