### ISSUE TITLE
Sending a plain string as a message value is not received on a wehbook subscription

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#116]
**Expected behavior:**
If a message is accepted by a FireFly node, whatever is in the `value` field should be put in the HTTP request body for a webhook subscription

**Observed behavior:**
When putting a plain string in the `value` field of a FireFly message, the HTTP request body on the received webhook is an empty object

**Comment by meeramn** [comment]
I would like to work on this as part of vGHC21 Open Source Code Day. Can you assign this to me?

**Comment by nguyer** [comment]
Sure! Let me know if you want to to talk about where to start on this one. Looking forward to OSD tomorrow!

**Comment by scaraclette** [comment]
Example on how to reproduce bug/how to connect via webhook using mock server. Testing via swagger:
1.  Have a firefly stack running via CLI.
2. Create a mock server in https://requestcatcher.com/. For example, I created a server as https://ff-webhook.requestcatcher.com/
3. Test via swagger by going to http://localhost:5000/api
4. To set subscription, at endpoint POST /namespaces/{ns}/subscriptions, post with the following body:
          {
            "transport": "webhooks",
            "name": "some_webhook_subscription",
            "options": {
              "url": "https://ff-webhook.requestcatcher.com/ff"
            }
          }
   It should return 201
5. Try sending a string broadcast message from the endpoint POST /namespaces/{ns}/messages/broadcast with an example body:
        {
          "data": [
            {
              "value": "hello world, this is some test data!"
            }
          ]
        }
6. In the request catcher for mock server https://ff-webhook.requestcatcher.com/, it should receive the message value "hello world, this is some test data!". However, the current bug is that the subscriber receives an empty object -> {}.

**Comment by meeramn** [comment]
PR for this issue https://github.com/hyperledger/firefly/pull/225
