### ISSUE TITLE
Firefly does not use the docker compose plugin

### ISSUE THREAD

**Issue by dimitry-dukhovny** [hyperledger/firefly#1165]
`ff remove ffnetwork`

Produced:

```
Error: an error occurred while running docker-compose. Is docker-compose installed on your computer?
```

We tried dropping a script called */usr/local/bin/docker-compose* that calls `docker compose ${@}` but got the same result. 
An `strace` showed it was checking the version of `docker-compose`.

**Comment by nguyer** [comment]
Hi @dimitry-dukhovny. In which version of the FireFly CLI are you encountering this issue? I think https://github.com/hyperledger/firefly-cli/pull/232 included a solution to this problem. That PR is part of FireFly `v1.2.0-alpha.1` and forward. That release will likely be finalized this week.

**Comment by dimitry-dukhovny** [comment]
Knowing the fix is coming suffices.  Thank you.

**Comment by nguyer** [comment]
Great, thanks!
