### ISSUE TITLE
Batch manager groups together messages with different signing keys

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1173]
The batch manager starts a separate processor for each signing context. However, it only looks at each message's identity, not the actual signing key:

https://github.com/hyperledger/firefly/blob/c42ad700cad0d167d08f152e76aa52fbedf6f2a9/internal/batch/batch_manager.go#L138

This means that if a single identity sends many messages with many signing keys, they can all get sent to the same batch processor. The messages whose signing key doesn't match the signing key of the batch will ultimately be rejected.

**Comment by peterbroadhurst** [comment]
Just to clarify, this is specific to:
- Private messages
- All using the same identity, backed by an off-chain node identity
- Choosing to use lots of different signing keys on-chain for anonymity
