### ISSUE TITLE
Introduce NoSQL database, with common e2e tests to SQLCommon

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#119]
The SQLCommon layer is very important across SQL databases as it:
- Reduces DB specific code
- Contains detailed e2e tests that are specific to the rules of each collection

However, there are some challenges when you look at taking the next step:
- The e2e tests run as UTs, and can only be run against the `ql` database
  - Cannot be used test migrations for other databases like PostgreSQL, SQLite etc.
  - Cannot be used to test non-SQL databases
- There is a lot of resource specific logic/optimization that must be applied to all databases
  - Collections with name uniqueness (namespaces, datatypes)
  - Collections with sequences that are used directly by code as `int64` (sequence is universal for natural sort order)
  - Collections with UUID as the key on the API (common, but not universal - note sequence is primary key)
  - Collections with Hash as the key on the API (rare, just `group` at time of writing - note sequence is primary key)

I note that some detailed exploration was performed of various ways to reduce the boilerplate in the SQLCommon layer (even further than was possible with the common insert/update functions and filtering).
Something like an ORM, where there's metadata describing each resource-collection, that is sufficient to allow a generic function to handle all the various types.
However, every approach tried came with pretty horrible trade-offs, where the caller would have to do type coercion, or the boilerplate just moved to a different layer. As such this was paused to be re-visited as part of this issue.

**Comment by shorsher** [comment]
Closing this issue. Please open a [FIR](https://github.com/hyperledger/firefly-fir) for a proposal and further discussion.
