### ISSUE TITLE
Postgres optimizations are not enabled correctly

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1199]
While troubleshooting #1196, I found that although I was using Postgres, the `MultiRowInsert` option was disabled. It's therefore likely some other Postgres optimizations are disabled by default as well.

Seems to be fallout from moving database configuration around between core and firefly-common (see https://github.com/hyperledger/firefly/pull/1110).

**Comment by matthew1001** [comment]
I've drafted PR https://github.com/hyperledger/firefly/pull/1197 to resolve this issue, but it will have to remain in draft until the pre-req PR https://github.com/hyperledger/firefly-common/pull/49 has been approved and we have a new `firefly-common` release.
