### ISSUE TITLE
Connecting Firefly to Custom Blockchain

### ISSUE THREAD

**Issue by CryptoDevving** [hyperledger/firefly#1238]
Hello,
How would I go about connecting my Polygon Edge custom chain to my firefly node?
I tried using evmconnect and ff init but I am having no success.

**Comment by nguyer** [comment]
Hi @CryptoDevving. I'm happy to help with this, but GitHub issues is not the best place for general questions and support. We use Issues for bug reports and tracking work items. I would encourage you to join the #firefly channel in the Hyperledger Discord server: https://discord.com/invite/hyperledger

I (and probably many other community members) are happy to help you out there. Thanks!
