### ISSUE TITLE
Failed stack initialisation in multi party mode connected to Polygon chain

### ISSUE THREAD

**Issue by denisandreenko** [hyperledger/firefly#1243]
Steps to reproduce:
Create stack in multiparty mode connected to the Polygon and provide address of deployed contract (ERC721 in this case)
`ff init dev 2 -n remote-rpc --remote-node-url <rpc-node> --chain-id 80001 --connector-config ~/projects/firefly/evmconnect.yml --contract-address 0x62368b268E7a5aD9C33590093AaaF569dd1182A2`

evnconnect.yml
`confirmations:
    required: 4
policyengine.simple:
    fixedGasPrice: null
    gasOracle:
        mode: connector
`
Then start the stack and you'll see that both FF cores are failed with:
`FF10111: Error from ethereum connector: execution reverted`

During initialization orchestrator runs or.multiparty.ConfigureContract(ctx) method in which are trying to get the version of the network for provider smart contract address by doing a request via emvconnector which returns the above error.

FF Core Container logs:
![Screenshot 2023-03-29 at 17 35 37](https://user-images.githubusercontent.com/16301397/228591515-ca1ef1e0-92c8-4e86-a3ed-2d4706a3d793.png)

**Comment by nguyer** [comment]
Hi @denisandreenko which smart contract did you compile and deploy to that address?

**Comment by denisandreenko** [comment]
@nguyer ERC721

```
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract MyNFT is ERC721 {
    constructor(string memory name, string memory symbol) ERC721(name, symbol) {
    }
}
```

**Comment by nguyer** [comment]
Ah that would be why then. The contract address there needs to point to the FireFly multiparty contract. You can find the source code for that here: https://github.com/hyperledger/firefly/blob/main/smart_contracts/ethereum/solidity_firefly/contracts/Firefly.sol

If you compile and deploy this contract, and set that as the value for `--contract-address` when you run `ff init` it should work just fine.
