### ISSUE TITLE
Integration test failure: insufficient_funds

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1244]
https://github.com/hyperledger/firefly/actions/runs/4559216926/jobs/8042927773

Identity definition batch pin is failing due to this (repeated) error in evmconnect:
`[32mevmconnect_0_1    |[0m [2023-03-30T00:22:30.835Z] ERROR evmconnect: Policy engine returned error for transaction default:5a524128-5fb1-4e58-9261-57f58e1d34e1 reason=insufficient_funds: %!s(<nil>) role=policyloop`

**Comment by Chengxuan** [comment]
In the logs I obtained, I can see calls to eth_gasPrice, these calls shouldn't be made as the default stack setup should use fixed gas price "0".

Two problems to be fixed:
- the migration logic to support the old `policyengine.simple` spelling is not working
- finish off https://github.com/hyperledger/firefly-transaction-manager/issues/57 by updating all the references of `policyengine.simple` to the new transaction handler spelling.

**Comment by Chengxuan** [comment]
This is fixed in the latest integration test run https://github.com/hyperledger/firefly/actions/runs/4578529639/jobs/8085549342 . Thanks for spotting it @awrichar
