### ISSUE TITLE
Options for Solidity contract to back token functionality

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#129]
Fungible and non-fungible token support is planned for FireFly across chains, beginning with Ethereum. One of the first architectural decisions involves selecting a Solidity contract as the reference implementation for tokens. Users may want (and may be encouraged) to define a custom contract in production, but the reference implementation should at a minimum:
1. be good enough for development usage
2. define the expected ABI for core token operations

Planned token functionality includes:
1. fungible and non-fungible token support
2. creation of multiple token types on a single smart contract (if possible)

For these requirements, ERC-1155 seems like the best starting point. However, due to its being a very general contract by nature, it may be difficult to find an existing implementation that exactly aligns with FireFly.

Summary of known ERC-1155 implementations:
* [OpenZeppelin ERC1155](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol): Extremely generic and not useful on its own. Implements safe transfers and balance tracking, but no mint or burn, no enforcement of supply or fungibility. Originally based on code by Enjin.
* [OpenZeppelin ERC1155 Preset - Minter/Pauser](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/presets/ERC1155PresetMinterPauser.sol): Extends the base contract with mint and pause functionality (and access control for those roles). Still no enforcement of supply or fungibility.
* [OpenZeppelin ERC1155 Extension - Supply](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/extensions/ERC1155Supply.sol): Mix-in for tracking total supply of each token. Doesn't explicitly track fungible vs. non-fungible, but gives some control for creating a token with a supply of 1 and using that knowledge to infer that the token is non-fungible. Did not find any preset/concrete implementation that brings in this extension.
* [Enjin ERC1155](https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155.sol): Original reference implementation. Basis for the OpenZeppelin implementation. Also not useful on its own.
* [Enjin ERC1155: Mixed Fungible/Mintable](https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155MixedFungibleMintable.sol): Extension to the Enjin base contract. Seems to do exactly what we want - explicitly tracks fungible vs. non-fungible tokens. Has not been updated in some time and was written against solidity 0.5.0.
* [Sequence ERC1155](https://github.com/0xsequence/erc-1155/blob/master/src/contracts/tokens/ERC1155/ERC1155.sol): Another base implementation (not connected to Enjin or OpenZeppelin). Also not useful on its own.
* [OpenSea ERC1155 Tradable](https://github.com/ProjectOpenSea/opensea-erc1155/blob/master/contracts/ERC1155Tradable.sol): Extension to the Sequence base contract. Provides mint, burn, and supply tracking. Has not been updated in some time and was written against solidity 0.5.12.

**Comment by awrichar** [comment]
Initial plan based on the available options is to create a thin custom layer on top of [OpenZeppelin ERC1155](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol), using the [Enjin ERC1155: Mixed Fungible/Mintable](https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155MixedFungibleMintable.sol) as a guideline.

**Comment by shorsher** [comment]
https://hyperledger.github.io/firefly/tutorials/tokens/
