### ISSUE TITLE
Add version Command to Core Binary

### ISSUE THREAD

**Issue by hfuss** [hyperledger/firefly#132]
Just like in [ethconnect](https://github.com/hyperledger-labs/firefly-ethconnect/blob/dd53ec2afc184da9b72eb92e83b1446d784c69f7/main.go#L26-L32) where we use `ldflags` to add build metadata (commit sha, tags, etc.) to the binary and log it at startup, we should then take it a step further and add a `version` command (similar to what `helm`, `kubectl`, `go` have) that then will output the same information.

**Comment by sushmita-manikandan** [comment]
I am interested to work on this.

**Comment by TheSwarnim** [comment]
Hi @nguyer, I'm interested to work on this issue. Please assign it to me

**Comment by nguyer** [comment]
Sure, thanks! I think @hfuss has some ideas of how this should be implemented, and has linked to an example from one of the other FireFly projects. Feel free to ping him on Discord if you want more info.

**Comment by TheSwarnim** [comment]
Thanks, @nguyer for your suggestion, I'll reach out to him on discord.

**Comment by TheSwarnim** [comment]
Hi @nguyer, I'm not able to test my command. Can you guide me or should I send a pr regarding this?
