### ISSUE TITLE
Broken link to Contributors Guide in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by PrathamSikka24** [hyperledger/firefly#1537]
The link to the contributors guide in the CONTRIBUTING.md file is broken. It currently points to a non-existent page and results in a 404 error.

Steps to Reproduce:

- Navigate to the [CONTRIBUTING.md](https://github.com/hyperledger/firefly/blob/main/CONTRIBUTING.md) file in the repository.
- Click on the hyperlink for the contributors guide.
- Observe the 404 error page.

Expected Behavior:
The link should direct users to the correct contributors guide page.

Actual Behavior:
The link directs to a 404 error page.

Link Causing Issue:
[contributors guide](https://hyperledger.github.io/firefly//contributors/index.html)

Suggested Fix:
Update the link to point to the correct URL for the contributors guide. If the correct URL is not known, please provide the correct path or update the documentation accordingly.

**Comment by EnriqueL8** [comment]
Thanks for raising this! Will fix this one
