### ISSUE TITLE
V1.3.2 Test Plan

### ISSUE THREAD

**Issue by EnriqueL8** [hyperledger/firefly#1574]
# Issue to track the Test Plan performed as part of the v1.3.2 release

**Comment by matthew1001** [comment]
Most of the manual testing for this release has been led by testing of the large-number support (see comment https://github.com/hyperledger/firefly/issues/1568#issuecomment-2326064650 on the original issue). Summary of the manual testing carried out on the FF 1.2 release candidate:

- [x] Create a single member EVM stack
- [ ] Deploy a contract through the FF CLI
- [ ] Create a contract API
- [ ] Create a listener
- [ ] Submit contract invocation with large number from Swagger (resulted in fix https://github.com/hyperledger/firefly/pull/1581)
- [ ] Submit contract invocation with large number from cURL
- [ ] Send a broadcast message containing a large-number data type
- [ ] Create a multi-party EVM stack
- [ ] Send a private message between parties using a numeric data type and a large number (resulted in fix https://github.com/hyperledger/firefly-ui/pull/225)
- [ ] View large-number data in the UI
- [ ] Mint and transfer ERC20 tokens using the sandbox UI

**Comment by EnriqueL8** [comment]
All completed ahead of the release!
