### ISSUE TITLE
Docs need to be updated to reflect new API endpoints

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#181]
We recently deprecated the `broadcast/message` and `send/message` endpoints in favor of a new format. The Getting Started tutorials https://labs.hyperledger.org/firefly/gettingstarted/gettingstarted.html and possibly other places should be updated to reflect that, so new developers don't start implementing new projects against the deprecated paths.

**Comment by shorsher** [comment]
Covered in https://hyperledger.github.io/firefly/reference/
