### ISSUE TITLE
Identity and signing key - architectural update

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#187]
We have some problems in the codebase today with a half-formed identity approach:
- A `Message` contains a single `Author` field, and it is ambiguous whether this is the identity or the signing key
- A shim `Identity` plugin designed to resolve an opaque string (such as a DID) into an identity on the platform... but without a definition of what that identity is
- The requirement for us to properly solve Fabric signing keys and round-trip these to events like we do in ethereum - currently blocking merge of #184 
- The fact that _both_ Ethereum and Fabric connectors have the concept of abstract lookup keys for actual signing keys (HD Wallets in Ethereum, and CN shortnames in Fabric)
- The requirement to handle anonymous signing of transactions for privacy preservation
- The requirement that the database representation of identity in a `Message` / `Token Pool` or `On-chain event` (coming soon) etc. must be consistent in every database of members allowed to see the object, even if they didn't submit the transaction

This issue will track a number of threads needed to resolve this.

**Comment by peterbroadhurst** [comment]
A few of us had a whiteboarding session, and the outcome was this beautiful wall of noise... and the conclusions below it:
![image](https://user-images.githubusercontent.com/6660217/132555862-a8c61cd5-deda-4a5f-b462-0799dceedaeb.png)

- [ ] We need to split `Author` into two fields - one representing identity, and one representing signing key
- [ ] We need to split `Key` as a different object to `Org` and allow multiple keys
- [ ] We need a consistent URI scheme for signing Keys
- [x] We need to create a matrix of how input identity, maps to the stored `Message` objects, and what verification is performed

**Comment by peterbroadhurst** [comment]
Here is first attempt at the matrix, for @jimthematrix to review as he works on the other items.

![image](https://user-images.githubusercontent.com/6660217/132556591-f454d893-3812-4d19-b052-1d38365d4602.png)

[firefly_message_identity_matrix_20210907.pdf](https://github.com/hyperledger-labs/firefly/files/7130760/firefly_message_identity_matrix_20210907.pdf)

**Comment by jimthematrix** [comment]
The matrix helps a lot!

Fabric doesn't really have an anonymous equivalent to an HD Wallet based signing key, because since it's x509 certificate based, the CA's identity must always be disclosed, which gives away the org identity it belongs to. Fabric doesn't allow a signer certificate that is issued by an unknown authority to interact with a channel.

I think this means with Fabric, private messages must either be unpinned, or be pinned with a known identity. whether the pinning identity is registered with the network map or not, does not change the fact that its identity can be verified and associated with a member org based on the cert itself.

**Comment by jimthematrix** [comment]
I wonder if we actually have 3 levels of identity objects: `Org =1--*=> Identity =1--*=> Key`

An org can have multiple registered signing identities. A signing identity can have multiple signing keys (as a result of key rotation, or an identity having a primary key and a backup key for recovery). I know we talked about some of this, but don't know if your model above was deliberately collapsing signing keys with signing identities.

**Comment by peterbroadhurst** [comment]
This is a great point.
Maybe next step is at a database/entity level, is to sketch out what information would be stored by FireFly in a 2 object, vs. 3 object model.

I guess in my mind to date, an `organization` in the Firefly is one possible _type_ of identity. A `node` always felt like another type. To your point that's probably incorrect thinking.

I'm hoping I can find a mechanical step forwards by introducing an `Identity Manager` component (distinct from a plug point), that helps with the mechanics of getting all this logic in one place in the code.

Then if we need to evolve the concept of identity a bit, at least it's a self-contained task with minimal side effects.

**Comment by peterbroadhurst** [comment]
The thing on Fabric I'd read about was: https://hyperledger-fabric.readthedocs.io/en/release-1.2/idemix.html
However, 99% case certainly feels like having a channel scoped to a set of verifiers where disclosing transaction submitters is considered low-risk metadata leakage. But probably a conversation for other threads and issues.

**Comment by peterbroadhurst** [comment]
@nguyer and I have been working on #192, which is intending to get the engineering started on implementing the split of `author` and `key`.

In doing this work, we will be carving out a place in the code that a governance plug point _should_ exist and does not today:

When adding a new root org to the network, it should be possible for plugins to provide external verification that this member is authorized to create a new root identity.

**Comment by peterbroadhurst** [comment]
Quick slide pulled together to aid the community discussion on 9/29

<img width="960" alt="firefly_discussion_identity_20210929" src="https://user-images.githubusercontent.com/6660217/135280185-6a514cfc-db7b-4b65-8975-8cf2f2d1d0bb.png">
[firefly_discussion_identity_20210929.pptx](https://github.com/hyperledger/firefly/files/7252368/firefly_discussion_identity_20210929.pptx)

**Comment by arsulegai** [comment]
This thread has great points to ponder upon. However, I see blockchain pinning of transactions and anonymous signature verification are stressed throughout in designing the solution. Idemix in Fabric attempts to dissolve an identity's authorized attributes but does less on anonymizing the issuer's identity. I had a different thought altogether about identity management at the connectors. But before that, it make sense to understand the current identity model in FireFly, could you please point me to more information?

**Comment by shorsher** [comment]
Closed in favor of further discussion and feedback in the FIR https://github.com/hyperledger/firefly-fir/pull/9
