### ISSUE TITLE
Prometheus Instrumentation

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#189]
We want to start building out robust metrics in FireFly for better operations. As a start, we need to create a `metrics` endpoint that Prometheus can scrape. This should be pretty easy with the HTTP handler built into the Prometheus Go library: https://github.com/prometheus/client_golang.

As a basic demonstration of the new metrics capabilities, we could just add a simple counter for the number of API calls that have been made to the node. Any time an API endpoint is called, it would simply increment a counter.

As a demo of this functionality, it would be great to see the metrics being reported in Prometheus itself. This could simply be a local instance of Prometheus scraping logs from FireFly nodes running locally, set up by the CLI. The FireFly CLI does not need to set up Prometheus.

**Comment by hfuss** [comment]
Re-reading this issue now that #321 is merged, and I think https://github.com/hyperledger/firefly-cli/issues/121 will address some of this but we will still need to add some custom metrics for FF to finish the vision of this issue.

@nguyer would you rather re-open this issue or creating a new issue for the custom metrics?
