### ISSUE TITLE
Support for smart contracts

### ISSUE THREAD

**Issue by glesaint** [hyperledger/firefly#194]
# Background

Firefly already solves the challenges of multi-party data flows, such as ensuring the consistency of a company's internal records when using a consortium's shared ledger as source of truth for these records. Users of public blockchains have similar challenges when it comes to ensuring the consistency of offchain applications with an onchain reference state. However, instead of agreed data formats and flows, what's agreed upon is the interface to smart contracts, such as ERC20 for tokens, or other dApps such as DeFi products.
This is currently under development https://labs.hyperledger.org/firefly/gettingstarted/custom_blockchain.html.

# Motivation

Very high security guarantees for multi-party process flows come when the logic is moved on-chain. 
While this introduces some issues with regards to data privacy, there are still a number of addressable use-cases.
In particular, Firefly could address the needs of existing public blockchain smart contract users (e.g. DeFi) when it comes to offchain integration.
A possible challenge will be the different state and execution models of different blockchains, and this issue is written in the context of Ethereum.

# Requirements

## Contracts    
- Contracts exist on a network, at an address, with a specific ABI
- Any function of the ABI should be available to the Firefly clients
- To support proxy patterns, we need to allow any ABI for any address
- For public networks, there is no need for Firefly to deploy contracts
- For public networks, there is no need for permissioned access to contracts

## Calls
- Smart contracts can return data without a transaction via calls
- Firefly clients should be able to make contract calls

## Transactions
- All functions of any contract should be executable via transactions
- Firefly clients should be able to send contract transactions, and receive the associated events if any

## Events
- Firefly clients should be able to watch contract addresses for desired events (e.g. ERC20 transfer)
- An 'event interface' should be defined so that offchain applications can interact with this data

# Outline
To be discussed with the community on how the above can be implemented.

**Comment by peterbroadhurst** [comment]
This is great. Almost precisely lines up with work in progress on architecture and engineering fyi @nguyer @jimthematrix @awrichar 

## Custom tokens

For ERC20 as a token standard there is another thread of engineering, that's pretty advanced at this point, to support Tokens (fungible and non-fungible) *including custom token implementations* (ERC20/ERC721/ERC1155 derivatives).

This goes beyond pure custom on-chain logic support, by providing the the off-chain API per a standardized token model that can work across multiple token implementations, including across protocols. 
Importantly, it includes packaging the work of building an off-chain cache of transaction history, that is required in any token based project.

The architecture embraces the fact that tokens will need on-chain logic customization, and also that likely mapping to a common API will require mapping. So there is an easy pluggable connector layer included -with a Typescript exemplar repo based on ERC1155 + OpenZeppelin + Ethconnect.

An update was provided by @awrichar on the most recent FireFly community call, Sep 15th:
https://wiki.hyperledger.org/display/labs/2021-09-15+FireFly+Community+Call

### Fully custom on-chain logic

As discussed elsewhere, custom smart contract submission/event functionality is available directly through ethconnect for Ethereum, and recently a trimmed version made available through fabconnect for Fabric.

What is being worked on at the FireFly core architecture level, is to solve many requirements listed here:
- Providing a broadcast

**Comment by shorsher** [comment]
Implemented in v1.

https://hyperledger.github.io/firefly/tutorials/custom_contracts.html
