### ISSUE TITLE
Secure compute architecture

### ISSUE THREAD

**Issue by glesaint** [hyperledger/firefly#195]
# Background

Blockchains, coupled with trusted compute techniques, and advances in cryptography allows us to build applications that are inherently secure, running on a new type of virtual machine with inherent security properties.

# Motivation

A lot of members of the Hyperledger community have a deep understanding of the capabilities offered by the upcoming 'secure compute' revolution. Members of the Ethereum, ZKP, MPC, FHE communities share a deep understanding of the new type of applications, services and computers we can now build.
By working closely together, and agreeing on an architecture for secure computing which goes beyond what each of us is working on, we can hopefully build products and tools that interact well with one another. Kind of like what the OSI model has achieved for the internet.

# Call to action

We're trying to outline a vision that the community agrees on, so that we can establish an architecture for secure compute.
The goal is to expand on the key concepts introduced by Firefly, https://labs.hyperledger.org/firefly/keyconcepts/multiparty.html, and get the word out to assemble a community who wants to make secure compute a reality.
For this purpose, we're releasing the https://www.securecompute.org/ manifesto and it seems very much aligned with the vision of the Firefly community.
We'd love to get feedback, especially on the proposed layer model, and practical proposals for problems we need to solve, these are outlined here. https://www.securecompute.org/atato-manifesto/how-we-will-solve-it

It's a long read, so we really appreciate anyone who'll take the time to read through this!

**Comment by shorsher** [comment]
Closing this issue in favor of the [FIR](https://github.com/hyperledger/firefly-fir) process.
