### ISSUE TITLE
Custom on-chain logic API unification - announce interface, invoke and subscribe

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#217]
... to be filled in by @nguyer, @jimthematrix, @awrichar, but opening to have number to refer to in diagrams

**Comment by peterbroadhurst** [comment]
To get the ball rolling, here's a diagram that represents my high-level understanding of the job at hand in the detailed design that will evolve in this issue.

<img width="960" alt="firefly_discussion_onchain_draft" src="https://user-images.githubusercontent.com/6660217/135336457-6722b90c-777a-426e-9cb5-a42d33c0427d.png">
:
[firefly_discussion_onchain_draft.pptx](https://github.com/hyperledger/firefly/files/7254588/firefly_discussion_onchain_draft.pptx)

**Comment by peterbroadhurst** [comment]
@jimthematrix has taken a lead on enhancing the raw connector interface, which is very mature in EthConnect, and evolving today in FabConnect.

In EthConnect today (not including below PR):
  - A set of registration capabilities for the ABI exist in EthConnect that are mature, but were designed without the above architecture, and specific to Ethereum.
    - Instead of copying these to FabConnect and duplicating them, we will move them up to FireFly
    - This means it's likely significant portions of Ethconnect will become deprecated over a time period
    - This deprecation time period might be long, due to the amount of production use of that connector today
    - The FireFly CLI has been coded using these EthConnect interfaces for registration of the simple "pinning" contract
      - Note contract compilation/deployment is **not** in scope for this enhanced architecture
    - The FireFly ethereum blockchain plugin uses these generated REST APIs for event subscription and invocation of the pinning contract
      - This existing code should be considered for refactor after the on-chain registration code is complete
- Invocation payloads are well defined, and can contain an in-line definition of the types, address, and method name
- Subscribe APIs _cannot_ contain in-line type information
  - They rely on pre-registration of the ABI within EthConnect to generate a REST API
  - An enhancement will be needed to allow a subscription API with in-line event type information, to remove the need for ABI registration at all within EthConnect

https://github.com/hyperledger/firefly-ethconnect/pull/154

**Comment by jimthematrix** [comment]
to visualize the two styles of endpoints, since we are making decisions on choosing one over the other, here are the call details of the fully parameterized generic endpoint vs. RESTful endpoint:

### Generic endpoint with full details in payloads
```json
POST /hook
{
    "headers": {
        "type": "SendTransaction"
    },
    "from": "0xa1aEE560bDBdA311964E4e709D89254bBe5a7AE5",
    "to": "0x2fe59d7bc95933e51327c2f51bc088380c5bc9cd",
    "params": [
        {
            "value": "4276993775",
            "type": "uint256"
        },
        {
            "value": "this is a string",
            "type": "string"
        }
    ],
    "gas": 1000000,
    "methodName": "set"
}
```

### RESTful endpoint
the following is proposed and implemented in hyperledger/firefly-ethconnect#154
```json
POST /contracts/0x2fe59d7bc95933e51327c2f51bc088380c5bc9cd/set?fly-from=0xa1aEE560bDBdA311964E4e709D89254bBe5a7AE5&fly-gas=1000000
{
    "$schema":  {
      "type": "function",
      "name": "set",
      "stateMutability": "nonpayable",
      "inputs": [
        {
          "name": "x",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": []
    },
    "x": "12346"
}
```

**Comment by peterbroadhurst** [comment]
For ethconnect specifically, the challenge isn't one of cleanliness of the API (don't mean to diminish that), it's about the code structure and re-use with what's there already.
I assert there's no need for consistency or overlap with FabConnect in this case (per the diagram, there are explicitly decoupled via the plugin code).

Here's the concerns with a revamp of the invocation code in Ethconnect:
- We have an API that's used in production, and supports passing types. If we introduce a new API with a different spelling, we need codepaths maintained for both. Worried about possibility of regressing one. I don't know of any reason we need to change the existing code to support FireFly calling it (beyond adding the ability to submit in-line type information in the subscribe - which is a separate part of the API).
- (Biggest worry) the whole of the `/contracts` endpoint, is tied up with code that is structured around generating REST APIs, and this has nothing to do with that. It's really complicated code, because it has to deal with a very complicated API that can be mapped to generated ABIs. Whether it's called `/hook` or just `/` or something else like `/firefly` or `/api/v2` I assert we need to keep the JSON-POST API separate in the codebase from the REST generated interface we're deprecating.
- The same JSON payload should be submittable via Kafka, as well as via HTTP. That is true in how the EthConnect code is structured today.
   - As an aside, I think this is important for both FabConnect and EthConnect - was raised on the community call today.

**Comment by jimthematrix** [comment]
Thanks for the additional background. I'm all for consolidating the endpoints and simplifying the code base (over time). Totally fine with the generic endpoint being the consolidated one going forward. Incidentally it's consistent with the style support by fabconnect (`POST /transactions`).

For the event subscriptions support, the PR hyperledger/firefly-ethconnect#154 adds it in the code path that currently subscribes to events behind the RESTful endpoints (`/abis/:abi/:event/subscribe` and others), I assume we want to add the ability to subscribe to events to the `POST /hook` (or the new name for it) endpoint as well, given that the RESTful endpoints are considered deprecated?

**Comment by peterbroadhurst** [comment]
> I assume we want to add the ability to subscribe to events to the POST /hook

I don't think that's necessary, as it's a separate one-time setup API action (rather than something you stream in).
However, I do think the thing that's missing is a `POST` `/api/v1/subscriptions` endpoint (filling out the `C` of the CRUD interfavce), rather than something under the `/abis` router.

**Comment by peterbroadhurst** [comment]
Making `/transactions` an additional `POST` route for the existing `/hook` makes sense to me too 👍

**Comment by jimthematrix** [comment]
> I do think the thing that's missing is a POST /api/v1/subscriptions endpoint

that's what I was proposing, only that I assumed the ability would be merged under the existing `POST /hook` endpoint given that it's being adopted as the main route going forward.

So just to confirm, we are going to have these endpoints:
`POST /api/v1/transactions`: with payload parameters to differentiate the target contract by address, method, input, etc and the inline schema
`POST /api/v1/subscriptions`: with payload parameters to differentiate the target contract by address, event name, etc. and the inline schema

is that correct?

**Comment by peterbroadhurst** [comment]
- > `POST /api/v1/transactions`: with payload parameters to differentiate the target contract by address, method, input, etc and the inline schema
  - ✅  - adding an alias to the _existing_ `/hook` endpoint on `/transactions` sounds fine, and low cost/risk
  - ❓  - do we want to add an `/api/v1/` prefix to existing routes? If we do this, think it should cover all routes
- > `POST /api/v1/subscriptions`: with payload parameters to differentiate the target contract by address, event name, etc. and the inline schema
  - ❓  - same comment as above applies for the `/api/v1` prefix
  - ✅  - here's an example payload from a `GET`, which will show what the `POST` would look like, with annotations on output only fields

```js
  {
    "created": "2021-01-01T01:00:35Z", // output only
    "id": "sb-d4baa8c5-fe53-4280-b8b0-2129afba5812",// output only
    "path": "/subscriptions/sb-d4baa8c5-fe53-4280-b8b0-2129afba5812",// output only
    "name": "mysubname",
    "stream": "es-12703181-65f3-411e-83df-897e74a9f9d4",
    "filter": {
      "address": [
        "0x0Be01cDfe811359D8935B741c340Cd22b3f7E75f"
      ],
      "topics": [
        [
          "0x5776ec96635c8e4aa0b57ebb539a02e60ff65013d475967f55c1e7cdde64f7bb"  // would need to be generated
        ]
      ]
    },
    "event": {
      "type": "event",
      "name": "UnstructuredAssetDefinitionCreated",
      "inputs": [
        {
          "name": "assetDefinitionID",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "author",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "name",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "isContentPrivate",
          "type": "bool",
          "internalType": "bool"
        },
        {
          "name": "isContentUnique",
          "type": "bool",
          "internalType": "bool"
        },
        {
          "name": "timestamp",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": null
    },
    "fromBlock": "latest"
  }
```

**Comment by shorsher** [comment]
Closing this in favor of ongoing discussion on the on-chain logic [FIR](https://github.com/hyperledger/firefly-fir/pull/2)
