### ISSUE TITLE
Token support

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#218]
FireFly should support the creation and tracking of both fungible and non-fungible tokens. Some of the key concepts that must be supported:
* Creating multiple types of tokens
* Minting, transferring, and burning tokens of a given type
* Tracking transaction history and current account balances (must include operations initiated by FireFly and also those initiated on-chain with no trigger from FireFly)
* Attaching data to a token transfer, for correlating off-chain items with the transfer event on-chain

The first connector will be focused on Ethereum tokens support via ERC1155. Source code for the connector is here: https://github.com/hyperledger/firefly-tokens-erc1155

This functionality is part of milestone #117.

Cross-chain functionality, including atomic swaps and the like, will not be part of this design effort (but will be part of a future item).

**Comment by awrichar** [comment]
This tracking issue is a bit late to the game, but tokens have been discussed in detail on these two community calls:
https://wiki.hyperledger.org/display/FIR/2021-06-30+FireFly+Community+Call
https://wiki.hyperledger.org/display/FIR/2021-09-15+FireFly+Community+Call

Below are a few slides from those discussions that informed the initial design:
![FireFly Architecture Episode 2 pptx](https://user-images.githubusercontent.com/1993829/135339774-5a821db0-0a29-4461-924e-5cd4a20fc2da.png)
![FireFly Architecture Episode 2 pptx (1)](https://user-images.githubusercontent.com/1993829/135339840-51a25d52-2ba2-41c1-8469-c9b8b4b0cf81.png)
![FireFly - Tokens Update](https://user-images.githubusercontent.com/1993829/135339875-d90ecaf4-fd58-4b17-88f7-fddde607df84.png)

**Comment by awrichar** [comment]
PRs merged to date:
#154 Add support for creating token pools
#162 Add "confirm" parameter when creating token pools
#163 Reject token pool events with duplicate info
#165 Rename token fields to match backend changes
#166 Add GET routes for token pools
#167 Handle token_pool_rejected, add new transaction type for token pools
#173 Add unit tests for tokens HTTPS plugin
#176 Align the "additionalInfo" for blockchain and token transactions
#177 Read "operator" field instead of "author" for token-pool event
#178 Add skeleton functionality for token accounts
#179 Supply requestId when creating token pools
#185 Pack all token pool info into "data" field
#193 Small fixes to token accounts
#201 Add additional fields to TokenPool
#202 Rename tokens "https" plugin to "fftokens"
#210 Move TokenPoolCreated handler into AssetManager
#212 Add "created" field to token pools, add some extra E2E checks

**Comment by awrichar** [comment]
Next pending (open) PRs:
#211 Announce token pool info via broadcast
#215 Add database types and route for listing token transfers

**Comment by awrichar** [comment]
As these have shaped up, this is the current surface area of the tokens API (current and planned endpoints):
```
POST /namespaces/{ns}/tokens/{type}/pools - create pool
GET /namespaces/{ns}/tokens/{type}/pools - list pools
GET /namespaces/{ns}/tokens/{type}/pools/{name} - get pool
GET /namespaces/{ns}/tokens/{type}/pools/{name}/accounts - list known accounts (i.e. that have ever had non-zero balance)
GET /namespaces/{ns}/tokens/{type}/pools/{name}/transfers - list all transfers that have occurred in this pool
POST /namespaces/{ns}/tokens/{type}/pools/{name}/transfers - perform a transfer within this pool
POST /namespaces/{ns}/tokens/{type}/pools/{name}/mint - perform a mint (actually this is identical to a transfer, but without a "from" or "tokenIndex")
```

The last one is a bit of an open question - I think we'll want a separate `/mint` API for clarity. Technically a mint is just a special case of transfer, but it feels like they should be separate API operations. Open to input on this point.

**Comment by jimthematrix** [comment]
the list of endpoints above look good to me.

just want to confirm that we have these following ones in the roadmap as well:
- `approve`: to allow a different account to spend on behalf of the token owner, aka the transaction submitter, this is required for use cases that involve an escrow or custody
- `transferFrom`: works together with `approve`, for the designated spender to spend out of the approver's account balance. this could be merged under `transfers` but would require an additional parameter in the `transfers` calls that are extraneous if the transfers are from the submitter's own balance
- `burn`: this is required for use cases such as token bridges

**Comment by awrichar** [comment]
@jimthematrix I was thinking `/transfer` should have both `from` and `to` parameters, with either defaulting to the author if unset (although it's an error if both are unset).

I also agree we should explicitly have `/burn` in parallel with `/mint` (even though it's also just a "special" kind of transfer, I think the dedicated API is good for clarity).

And we do definitely need a way to set approvers. Not sure if that'll be a simple `/approve` or a whole set of role-management endpoints (one other related operation is setting who can mint in a given pool). Haven't given this a ton of thought yet.

**Comment by awrichar** [comment]
Updated #215 to include the POST routes for `/mint` and `/transfers` as discussed above.

**Comment by awrichar** [comment]
Also put up a PR for burn support in the ERC1155 connector: https://github.com/hyperledger/firefly-tokens-erc1155/pull/29
Once that is merged, it will be simple to add support in FireFly.

**Comment by awrichar** [comment]
Burn support is now merged in the connector, so #215 has been updated again to include a `/burn` route.

**Comment by awrichar** [comment]
Diagram of the new two-step create+announce flow for pool creation, introduced in #211:
<img width="1101" alt="FireFly Token Pool - Creation Internals" src="https://user-images.githubusercontent.com/1993829/135640012-53ee9816-4bc5-42b4-b4f1-6ee2e309b0c7.png">

**Comment by awrichar** [comment]
And a higher-level look at what the validation flow looks like on the other nodes - placeholder logic for this validation was introduced in #211, but the final implementation is tracked by #222:

<img width="1231" alt="FireFly Token Pool Validation" src="https://user-images.githubusercontent.com/1993829/135640318-e1eb9298-3921-4c92-8295-6b62129fcc93.png">

**Comment by awrichar** [comment]
Basic/standalone token support is now in mainline with the merge of #215 (and a small follow-on in #239).

Now the piece that ties it all together:
#245 Allow sending a message with a token transfer

**Comment by awrichar** [comment]
Noted another bit of functionality that may be desirable for 1.0:
#326 Allow setting a URI for NFTs
