### ISSUE TITLE
Websocket: response does not implement http.Hijacker - when metrics enabled

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#370]
When connecting to a firefly node from a websocket client, connections are being refused with an error message of: `WebSocket upgrade failed: websocket: response does not implement http.Hijacker`

Steps to reproduce:
1. Create Firefly stack
2. Open a websocket client:
    - [Chrome Extension](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo/related?hl=en)
    - [Node](https://www.npmjs.com/package/websocket)
    - Any other ways you use to make websocket connections
3. Try to connect to `ws://localhost:5000/ws?namespace=default&ephemeral&autoack&filter.events=message_confirmed`
4. If you're able to reproduce, you'll see this error message in the firefly logs: `WebSocket upgrade failed: websocket: response does not implement http.Hijacker`

**Comment by nguyer** [comment]
I tried reproducing this using the latest release, and I'm unable to reproduce the issue with either the Chrome extension listed above, or with `websocat`. Here are the images I have in my stack

```
Container         Repository                    Tag           Image Id       Size
-------------------------------------------------------------------------------------
dataexchange_0    <none>                        <none>        3608d80ec12e   246.3 MB
dataexchange_1    <none>                        <none>        3608d80ec12e   246.3 MB
ethconnect_0      <none>                        <none>        eb3a19351cd9   112.7 MB
ethconnect_1      <none>                        <none>        eb3a19351cd9   112.7 MB
firefly_core_0    ghcr.io/hyperledger/firefly   v0.11.4       a2db642370cd   44.86 MB
firefly_core_1    ghcr.io/hyperledger/firefly   v0.11.4       a2db642370cd   44.86 MB
geth              ethereum/client-go            release-1.9   e1fadad25027   44.81 MB
ipfs_0            ipfs/go-ipfs                  latest        3e1ffbe25944   77.18 MB
ipfs_1            ipfs/go-ipfs                  latest        3e1ffbe25944   77.18 MB
tokens_0          <none>                        <none>        309b25221e2e   460 MB
tokens_1          <none>                        <none>        309b25221e2e   460 MB
```

**Comment by eberger727** [comment]
The issue was that the prometheus middleware was not implementing the `http.Hijacker` interface. Fix is in #371.

**Comment by peterbroadhurst** [comment]
@eberger727 - hope you don't mind me re-opening.

- Was this a regression caused when we introduced our prometheus middleware?
- Was that shipped in a previous release?
- What is the state of the v0.10.4 release? https://github.com/hyperledger/firefly/releases/tag/v0.11.4

**Comment by peterbroadhurst** [comment]
I managed to talk to @hfuss - and the problem only occurs when metrics is enabled 👍 
I do think this bug should close with the PR (rather than ahead of it)
