### ISSUE TITLE
Read only query support

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#401]

**Comment by TheSwarnim** [comment]
Hi @nguyer, I'm Swarnim and I've have reached out to you via @peterbroadhurst . I'm interested in working in this project, and have good background in programming and some open source contribution in past. I want to get involved in this project. I'll be very greatful to you if you get involved in this project.

**Comment by nguyer** [comment]
Hi @TheSwarnim! Glad to hear your interested in working on FireFly! This particular issue, and several others that were just created yesterday need some more details filled in - I'm going to be working on that. But I'm happy to connect with you directly to chat about getting involved in the project. I'll send you an email directly and we can go from there.

**Comment by TheSwarnim** [comment]
Thanks @nguyer
