### ISSUE TITLE
Fill in swagger field descriptions

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#402]

**Comment by awrichar** [comment]
One in particular I want to be sure doesn't fall through the cracks - this field description is populated but is now inaccurate:
https://github.com/hyperledger/firefly/blob/f02facb298ad071f019f08e4a879b4e0352c8ecc/internal/i18n/en_translations.go#L72

As of #403, the operators are a bit different, and it would be great if we could include a link to the full documentation at https://github.com/hyperledger/firefly/blob/main/docs/reference/api_query_syntax.md.
