### ISSUE TITLE
Error on tokens -> accounts tab in firefly UI

### ISSUE THREAD

**Issue by mkashgarian** [hyperledger/firefly#416]
GET /tokens/accounts/0xe380f179aeb554c7456ae490b48fb1c5489459cd/pools?limit=4
response:
error fetching token pools for account 0xe380f179aeb554c7456ae490b48fb1c5489459cd

No accounts are showing up in the accounts tab because of this failed call

**Comment by mkashgarian** [comment]
FF10115: Database query failed: pq: for SELECT DISTINCT, ORDER BY expressions must appear in select list

**Comment by peterbroadhurst** [comment]
Whatever the fix is here, would be good to ensure the E2E test gets updated to make this call - as when new databases come up in the future this might be a key "special case" that developers need to check functions.
