### ISSUE TITLE
Intermittent Fabric e2e error

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#423]
https://github.com/hyperledger/firefly/runs/4877610909?check_suite_focus=true

```
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: Error constructing Docker VM Name. 'dev-fabric_peer-e2e_k0c2ysighkhdofikeduo--8a7a4e0277bc9bc9190c54ba253f786eace914a96627966aa0e3eb504183ba23-b6310a686e9fda4e70f20f34e24ae6b5c021f3c20457cd9bbfe4fbac8e071a7e' breaks Docker's repository naming rules
```

**Comment by nguyer** [comment]
Fabric uses a regex to check the name that a chaincode container will have to make sure it will be valid before starting it:
https://github.com/hyperledger/fabric/blob/main/core/container/dockercontroller/dockercontroller.go#L37

We're currently using a nanoid for uniqueness in the chaincode name that we generate. There is a chance that the nanoid ends in a `-` or a `_` based on its default vocabulary: https://github.com/aidarkhanov/nanoid/blob/v2.0.5/nanoid.go#L13

If this happens, when fabric appends some other ID on the end of it, it uses a `-` as a separator which then ends up failing to match its regex.

I think altering the nanoid's vocabulary to remove `-` and `_` for this specific call should fix it.
