### ISSUE TITLE
Make endpoint optional in DX

### ISSUE THREAD

**Issue by gabriel-indik** [hyperledger/firefly#433]
The current data exchange plugin uses HTTPs as the transport for P2P communications. Because of this the P2P endpoint is provided to FireFly via the `/api/v1/id` API so it can be broadcasted to other members. Note however that other DX implementations may rely other transports which do not require a P2P endpoint. In summary, the `endpoint` property should only be broadcasted to other members if such property is returned by the `api/v1/id` API in DX.

**Comment by gabriel-indik** [comment]
One alternative to make the plugin more extensible would be to define one field that will always be present for any DX (id) and then a group of fields that are specific to a particular DX grouped under a new property which could be called "args".
For example, in DX HTTPS it would be:

```
"id": "someId"
"args": {
  "cert": "X509Cert",
  "endpoint": "https://myendpoint.io"
}
```
For others it could be:
```
"id": "someId"
"args": {
  "custom1": "someValue",
  "custom1": "someOtherValue"
}
```

**Comment by awrichar** [comment]
What it looks like to me, is that FireFly stores the entire JSON blob returned by `/api/v1/id` internally as "endpoint". It expects the blob to have one special key called "id", but other than that, it may contain anything. This JSON is then packed into the node registration message, and will be directly used by all nodes in their PUT to `/api/v1/peers/{id}`. So it seems fairly extensible as-is.

**Comment by awrichar** [comment]
https://github.com/hyperledger/firefly/blob/a3992b8953a3dc7cc7c44e56978c3de8bcaefcb0/internal/dataexchange/dxhttps/dxhttps.go#L138

https://github.com/hyperledger/firefly/blob/a3992b8953a3dc7cc7c44e56978c3de8bcaefcb0/internal/dataexchange/dxhttps/dxhttps.go#L148

**Comment by gabriel-indik** [comment]
Thank you for looking into this @awrichar I'll close this issue as it looks like we are good with the code it is now.
