### ISSUE TITLE
Websocket test: close of closed channel

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#445]
Websocket unit tests are intermittently failing with "close of closed channel".

https://github.com/hyperledger/firefly/runs/4940262645?check_suite_focus=true

```
panic: close of closed channel

goroutine 74 [running]:
github.com/hyperledger/firefly/pkg/wsclient.NewTestWSServer.func1.1(0xc0003fc7e0, 0xc000363600, 0xc000010128)
	/home/runner/work/firefly/firefly/pkg/wsclient/wstestserver.go:45 +0x10e
created by github.com/hyperledger/firefly/pkg/wsclient.NewTestWSServer.func1
	/home/runner/work/firefly/firefly/pkg/wsclient/wstestserver.go:40 +0x16c
FAIL	github.com/hyperledger/firefly/pkg/wsclient	0.071s
```

This is potentially a side-effect (or an alteration of the underlying original bug) introduced by #420.

**Comment by awrichar** [comment]
https://github.com/hyperledger/firefly/runs/4972849059?check_suite_focus=true

**Comment by awrichar** [comment]
Is this yet another flavor of a similar issue?
https://github.com/hyperledger/firefly/runs/5058705964?check_suite_focus=true

**Comment by peterbroadhurst** [comment]
Think this is something sufficiently different, to be tracked in a new issue.
Think it will naturally become redundant when batch logic is revamped (next week) - but still good to have.

**Comment by peterbroadhurst** [comment]
Moved to https://github.com/hyperledger/firefly/issues/445

Closing this one out.
