### ISSUE TITLE
Add an event that is emitted when a new FireFly transaction begins on the local node

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#450]
See https://discord.com/channels/905194001349627914/935885156391223336/935943327721852938

- Add a new event type that is ~`local_transaction_submission`~ `transaction_submitted` that is emitted on a node, when it instigates a new transaction, but you only get that event on your local node
- Allows the UI to have a left-column of the events/activity view showing only those (rather than trying to reverse engineer which events are "ours")

**Comment by peterbroadhurst** [comment]
When implementing this, I think it's worthwhile to add the batch optimization fields to the Database layer for transactions, as that piece of work fits well with needing to evaluate each codepath that creates a transaction to determine if it should emit this event.

**Comment by peterbroadhurst** [comment]
@awrichar - feels like there's an overall documentation exercise that this fits into, where we describe the overall transaction/event model more helpfully to users. I wonder if the artefacts created for that should be rolled up into a FIR?

**Comment by awrichar** [comment]
I would propose `transaction_submitted`, to fit more with the "thing_verbed" structure of other events.

**Comment by awrichar** [comment]
And yes, once we figure out what the Transaction / BlockchainEvent / Event model is, we should definitely write it down 🤪 ongoing discussions on Discord for that.
