### ISSUE TITLE
FF-Perf: Websocket events appear to be dropped

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#493]
Test: 25 broadcasts, 25 private messages, one subscription

In this test, 25 workers were kicked off for both broadcasts and private messages. Shortly after the test is kicked off, workers are not receiving websocket events, preventing them from proceeding. The `ff-perf.log` has logs of message IDs and event IDs that can be used to correlate to the firefly logs that are also attached. Every minute, the perf test checks for messages that have not been confirmed in > 1 minute, do a `Ctrl+F` for `Delinquent Messages` and you will see the messageID that has not been confirmed yet, along with the time it was sent at.

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/17093033/153029391-86ea67da-340c-4122-a559-b6248fb041b8.png">

[log_ethconnect_0.log.zip](https://github.com/hyperledger/firefly/files/8025588/log_ethconnect_0.log.zip)
[log_firefly_core_0.log.zip](https://github.com/hyperledger/firefly/files/8025589/log_firefly_core_0.log.zip)
[ff-perf.log](https://github.com/hyperledger/firefly/files/8025590/ff-perf.log)

**Comment by eberger727** [comment]
Logs for commit `d90d176` to main
[log_firefly_core_0.log.zip](https://github.com/hyperledger/firefly/files/8025407/log_firefly_core_0.log.zip)
[log_ethconnect_0.log.zip](https://github.com/hyperledger/firefly/files/8025408/log_ethconnect_0.log.zip)
[ff-perf.log](https://github.com/hyperledger/firefly/files/8025409/ff-perf.log)

**Comment by eberger727** [comment]
Run after commit `82f55af`. Looks like events are not being sent back at all, or deadlock is occuring.
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/17093033/153051090-a48ea93e-4ab2-497e-8df7-b27615a03688.png">
[ff-perf.log](https://github.com/hyperledger/firefly/files/8026453/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8026454/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8026455/log_firefly_core_0.log)

**Comment by peterbroadhurst** [comment]
Quick script to extract how many times we see each msgid in the list:
```sh
for msgid in `grep 'Sent with Message ID' ff-perf.log | awk '{ print $9 }'`; do echo "   $msgid"; grep -c "$msgid" ff-perf.log; done  | head -n 100
```

**Comment by eberger727** [comment]
Ran again with new logs
[ff-perf.log](https://github.com/hyperledger/firefly/files/8026699/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8026701/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8026702/log_firefly_core_0.log)

**Comment by peterbroadhurst** [comment]
After #496 the run here shows this:

```
{"log":"[2022-02-08T19:00:14.904Z]  WARN Mismatched nexthash or author group=56913fa99c1b3efb491845762e4b1d43eb4c02dde916a694a8bb93fa51a6d00d topic=default context=8047f2adddffc76a145086d3a6d1b672dade28979b5bdf28ea880376b74c97d0 pin=672e60525642b2e39650252d152ee549042f44520c6861321fe34b49e93f2e57 nextHash=\u003cnil\u003e dbtx=Y1GWIkK1 pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T19:00:14.904190859Z"}
```

Chasing this context back, I found this was the last pin that was committed:

```
{"log":"[2022-02-08T19:00:13.509Z] DEBUG Incrementing NextPin=752808d9080cdc4f0ffe5defdb3070db822179f85b78280ede1d92a56e587903 - Nonce=22 Topic=default Group=56913fa99c1b3efb491845762e4b1d43eb4c02dde916a694a8bb93fa51a6d00d NewNextPin=f1eb02cdff4d38fa86f406542d7b1ae51b138caf2d56301ba25580ef54c63de4 dbtx=U9YVIdnU pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T19:00:13.509847559Z"}
```

Then the next one doesn't get aggregated:

```
{"log":"[2022-02-08T19:00:13.510Z] DEBUG Incrementing NextPin=f1eb02cdff4d38fa86f406542d7b1ae51b138caf2d56301ba25580ef54c63de4 - Nonce=23 Topic=default Group=56913fa99c1b3efb491845762e4b1d43eb4c02dde916a694a8bb93fa51a6d00d NewNextPin=1072abefdd229b4acd6f0a111a0ed1ad5ad8303b4dd2240461e8cb68c3d79c03 dbtx=U9YVIdnU pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T19:00:13.510862388Z"}
{"log":"[2022-02-08T19:00:13.510Z] DEBUG Aggregating pin 0000000030 batch=b92d2c71-3efa-47e3-bacb-ba33451b9940 hash=1072abefdd229b4acd6f0a111a0ed1ad5ad8303b4dd2240461e8cb68c3d79c03 masked=true dbtx=U9YVIdnU pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T19:00:13.510878976Z"}
```

Adding more debug

**Comment by eberger727** [comment]
Running with only broadcasts - 25 workers:
[ff-perf.log](https://github.com/hyperledger/firefly/files/8026835/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8026836/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8026837/log_firefly_core_0.log)

**Comment by peterbroadhurst** [comment]
The above broadcast run shows many messages sent, then `c568abbe-881e-43c9-a57c-8e133ec60caa` gets stuck with:

```
{"log":"[2022-02-08T19:13:30.211Z] DEBUG Message c568abbe-881e-43c9-a57c-8e133ec60caa pinned at sequence 215 blocked by earlier context 7\ufffd\ufffd\ufffd\ufffd\u0019h}\u0013/\ufffd\ufffdQܦ)\ufffdd\ufffdĕ\ufffd\ufffdA\ufffd\ufffd\u0013:3\ufffdh\ufffd at sequence 206 dbtx=o2e59tT9 pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T19:13:30.211291916Z"}
```

**Comment by eberger727** [comment]
25 broadcast/25 private - Only one message succeeds before test halts
[ff-perf.log](https://github.com/hyperledger/firefly/files/8027160/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8027161/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8027162/log_firefly_core_0.log)

**Comment by peterbroadhurst** [comment]
Latest run investigation ongoing to see why the first message is not matching here:

```
{"log":"[2022-02-08T20:13:21.515Z] DEBUG Aggregating pin 0000000005 batch=94870286-6ffe-4f96-abdd-046ee1506248 index=0 hash=5539a8f94dc5d76196247e1bf756c856570e780070f0fe0d87a602719452f7ee masked=true dbtx=NNgyCqWj pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T20:13:21.51606254Z"}
{"log":"[2022-02-08T20:13:21.522Z] DEBUG Group=fdacb9a418887b4e4388b38b2b91d70d20f35f6c988af8d276bfbd4006ca4bcc topic=default context=b17d858f3d37d4fa4c4812091c020686431b9fb6d3dc32ff20717a1ba09496d4 zeroHashes=[0cb7504e98fab01e5c98791c410aa499a8f12d0bc9107e54275bc67703041ce3 733ef69f3711c29bf2c5c66605e4e197f129f35123a4c05929f8f4fe605bda30] dbtx=NNgyCqWj pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T20:13:21.522634133Z"}
{"log":"[2022-02-08T20:13:21.522Z]  WARN No match for zerohash on context: group=fdacb9a418887b4e4388b38b2b91d70d20f35f6c988af8d276bfbd4006ca4bcc topic=default context=b17d858f3d37d4fa4c4812091c020686431b9fb6d3dc32ff20717a1ba09496d4 pin=423e71f8e95dee03dd01f60dda659e3046f3032e57e7afaab4322855969daa9c dbtx=NNgyCqWj pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-08T20:13:21.522731251Z"}

```

**Comment by eberger727** [comment]
25 broadcast/25 private - More debug logs
[ff-perf.log](https://github.com/hyperledger/firefly/files/8027462/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8027463/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8027464/log_firefly_core_0.log)

**Comment by eberger727** [comment]
25 broadcast/25 private - after #499
[ff-perf.log](https://github.com/hyperledger/firefly/files/8028150/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8028151/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8028152/log_firefly_core_0.log)

**Comment by peterbroadhurst** [comment]
Looks like a rewind issue maybe in this one:

```
{"log":"[2022-02-08T23:04:52.318Z] DEBUG Marking rewind to sequence=35 (previous=27) pid=1 role=batchmgr\n","stream":"stderr","time":"2022-02-08T23:04:52.318674632Z"}
```

But we don't go back and pick up `6736bf65-88bb-4f68-9cdc-ad322a3107f4`

**Comment by peterbroadhurst** [comment]
But we did rewind:
```
{"log":"[2022-02-08T23:04:52.411Z] DEBUG Rewinding to sequence=27 pid=1 role=batchmgr\n","stream":"stderr","time":"2022-02-08T23:04:52.411389994Z"}
```

**Comment by peterbroadhurst** [comment]
That's a simple one - we need to wind back to one before the message 🤦

**Comment by peterbroadhurst** [comment]
I've added https://github.com/hyperledger/firefly/pull/499/commits/8bd5fd3d47b0920b9d91481fbe6d707570660268 to #499

**Comment by eberger727** [comment]
50 broadcast/50 private
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/17093033/153487812-02ff61bd-cd37-42ea-b8a1-7b41055705c6.png">
[ff-perf.log](https://github.com/hyperledger/firefly/files/8043950/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8043951/log_ethconnect_0.log)
[log_firefly_core_0.log](https://github.com/hyperledger/firefly/files/8043952/log_firefly_core_0.log)

**Comment by eberger727** [comment]
50 broadcast/50 private - Runs for 15 minutes before private messages see issues
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/17093033/153492898-9da1d060-5ac5-4c28-8cee-946ca661b28b.png">
[ff-perf.log](https://github.com/hyperledger/firefly/files/8044129/ff-perf.log)
[log_ethconnect_0.log.gz](https://github.com/hyperledger/firefly/files/8044130/log_ethconnect_0.log.gz)
[minilog_firefly_core_0.log.zip](https://github.com/hyperledger/firefly/files/8044161/minilog_firefly_core_0.log.zip)

**Comment by peterbroadhurst** [comment]
^^^ was from #501 at commit https://github.com/hyperledger/firefly/pull/501/commits/4630c3d625672b38ce79e0ff2ae1f914be4de26e

**Comment by peterbroadhurst** [comment]
Investigating worker `51` message `024f58d5-0a96-4b30-b363-7a9a3676356b` in the delinquent list:

Previous message:

```
[36mINFO[0m[2022-02-10T20:32:11.630] 
	51 - Received 
	51 --- Event ID: 4ea61552-2786-4f55-bfea-0b1d52a5a851
	51 --- Message ID: a3502bd5-1a61-41ac-a807-daaa4e4ea819 
[36mINFO[0m[2022-02-10T20:32:11.630] 51 <-- msg_private Finished   
```

Sent stuck message: 

```
[36mINFO[0m[2022-02-10T20:32:11.683] 51 --> msg_private Sent with Message ID: 024f58d5-0a96-4b30-b363-7a9a3676356b 
```

```
[33mWARN[0m[2022-02-10T20:33:58.613] Delinquent Messages:
{
  "024f58d5-0a96-4b30-b363-7a9a3676356b": "2022-02-10T20:32:11.683201247Z",
```

I can see it was confirmed ok:

```
{"log":"[2022-02-10T20:32:14.335Z]  INFO Emitting message_confirmed 35969a25-0f49-4167-8994-a2bd715182ef for message default:024f58d5-0a96-4b30-b363-7a9a3676356b dbtx=R9y8SkiY pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-10T20:32:14.335614529Z"}
```

The **previous** event/message was dispatched on the WebSocket here:
```
{"log":"[2022-02-10T20:32:11.659Z] DEBUG Dispatching websockets event: 0000037490/cb9a4040-197b-42fb-be3f-b8c8e7ca2970 [message_confirmed]: ref=default/aebf20b8-5ad6-4c7a-8213-a7fa0e26011f pid=1 role=ed[d2ff7b72-504d-40dd-ab3e-e325c2b7a5d9] sub=3cf508e4-21a7-4f00-8ad0-a6d08a0703d0/default:perf_54c7faaf-ad...\n","stream":"stderr","time":"2022-02-10T20:32:11.659697115Z"}
{"log":"[2022-02-10T20:32:11.660Z] DEBUG Response for websockets event: 0000037490/cb9a4040-197b-42fb-be3f-b8c8e7ca2970 [message_confirmed]: ref=default/aebf20b8-5ad6-4c7a-8213-a7fa0e26011f rejected=false info='' pid=1 role=ed[d2ff7b72-504d-40dd-ab3e-e325c2b7a5d9] sub=3cf508e4-21a7-4f00-8ad0-a6d08a0703d0/default:perf_54c7faaf-ad...\n","stream":"stderr","time":"2022-02-10T20:32:11.66066805Z"}
```

**Comment by peterbroadhurst** [comment]
Moved this issue over to https://github.com/hyperledger/firefly/issues/508

**Comment by eberger727** [comment]
50 broadcasts/50 private messages - Ran for 9 hours before running out of space on the VM:
![image](https://user-images.githubusercontent.com/17093033/153629486-cb9474d5-77d3-4077-bbff-728d57f1f422.png)

**Comment by eberger727** [comment]
50 broadcasts/50 private messages - 1 hour run with https://github.com/kaleido-io/firefly/tree/batch-v2
<img width="1704" alt="image" src="https://user-images.githubusercontent.com/17093033/153639281-f797e979-3b5b-413f-a7c5-a480c341e3a8.png">

**Comment by eberger727** [comment]
100 broadcasts / 100 private messages. Looks Like a deadlock on the database occurred around 1:45.
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/17093033/153652189-a2b5acdd-8a26-4cf8-8593-8f043e4ab0a2.png">

[ff-perf.log](https://github.com/hyperledger/firefly/files/8050959/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8050960/log_ethconnect_0.log)
[log_firefly_core_0.log.gz](https://github.com/hyperledger/firefly/files/8050961/log_firefly_core_0.log.gz)

**Comment by awrichar** [comment]
Problematic log snippet:
```
{"log":"[2022-02-11T18:45:25.771Z] ERROR batch persist attempt 1: FF10345: Database lock failed: pq: deadlock detected d=pinned_broadcast p=default|did:firefly:org/410d158a-fd16-42f4-9967-2defdaa037f8| pid=1 role=batchmgr\n","stream":"stderr","time":"2022-02-11T18:45:25.771484834Z"}
{"log":"[2022-02-11T18:45:25.856Z] ERROR SQL lock failed: pq: deadlock detected sql=[ LOCK TABLE \"events\" IN EXCLUSIVE MODE; ] dbtx=WlA0qW71 pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-11T18:45:25.856929069Z"}
{"log":"[2022-02-11T18:45:25.856Z] DEBUG SQL\u003c- update affected=1 dbtx=v8QMBMDj pid=1 role=event-manager\n","stream":"stderr","time":"2022-02-11T18:45:25.857096058Z"}
{"log":"[2022-02-11T18:45:25.857Z] DEBUG SQL-\u003e update: UPDATE messages SET cid = $1, mtype = $2, author = $3, key = $4, created = $5, namespace = $6, topics = $7, tag = $8, group_hash = $9, datahash = $10, hash = $11, pins = $12, state = $13, confirmed = $14, tx_type = $15, batch_id = $16 WHERE hash = $17 AND id = $18 dbtx=v8QMBMDj pid=1 role=event-manager\n","stream":"stderr","time":"2022-02-11T18:45:25.857390045Z"}
{"log":"[2022-02-11T18:45:25.857Z]  WARN SQL! transaction rollback dbtx=WlA0qW71 pid=1 role=aggregator\n","stream":"stderr","time":"2022-02-11T18:45:25.857695506Z"}
{"log":"[2022-02-11T18:45:25.857Z] ERROR process events attempt 1: FF10345: Database lock failed: pq: deadlock detected pid=1 role=ep[ff_system:ff_aggregator]\n","stream":"stderr","time":"2022-02-11T18:45:25.858083752Z"}
```

Based on these logs, it's quite likely that the deadlock is occurring between here, where we submit a new transaction (which locks the events table):
https://github.com/hyperledger/firefly/blob/b7e8078696dac1d26a00b0c35f204aa22c863609/internal/batch/batch_processor.go#L465

And "something" in the events handling here:
https://github.com/hyperledger/firefly/blob/b7e8078696dac1d26a00b0c35f204aa22c863609/internal/events/event_poller.go#L223

The problem is most likely because the batch processor acquires the lock on the events table, but then goes on to update other tables while still holding that lock. If those other tables are locked by some other thread, deadlock can occur.

The best solution here appears to be ensuring that acquiring the table lock (and inserting any events) is always the _very last_ thing to occur before committing a database transaction. That way, the table lock is always short-lived and will never deadlock with something else.

**Comment by eberger727** [comment]
This issue has been resolved in the above PR
