### ISSUE TITLE
Contract listener subscribes from block 0 by default

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#585]
Right now by default if I create a contract listener, it subscribes from block `0` by default. The default behavior for **Subscriptions** is to subscribe from the current block, by default. The inconsistency between these two is confusing. Contract listeners should have default behavior that is consistent with Subscriptions.

**Comment by awrichar** [comment]
I think in previous discussions, we've said the default should probably be from the current block, instead of 0. And then we need a way to specifically subscribe from 0 or any other block (via a blockchain-agnostic config, similar to the "location" object for smart contracts).
