### ISSUE TITLE
Event listener creation is missing from Contract API swagger

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#660]
There doesn't seem to be any routes generated on the OpenAPI/Swagger for a Contract API, that give my application the ability to subscribe to events:

https://github.com/hyperledger/firefly/blob/4c29266ede1d525e409715ad0658a2b5344a1db9/internal/oapiffi/ffi2swagger.go#L45-L48

This seems like a big omission. If I publish an API I want it to describe everything the application can do with that smart contract. As well as short cuts to invoking/querying methods, I assert it should definitely include shortcuts to ~subscribing~ listening to events. Otherwise, how as an application would I know the events I can listen+subscribe to?

As an app dev, I would also expect to be able to query whether I already have a listener for those events on the same API - without needing to go to a different API and do some complicated filtering there. Or else to have a clear description available to me of how I should determine if I'm not already listening, and need to create a new listener.

**Comment by awrichar** [comment]
Fixed in https://github.com/hyperledger/firefly/pull/696
