### ISSUE TITLE
Multiple Token Connectors Bug

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#723]
I have a stack with 2 token connectors (erc1155 and erc20_erc721), I send a POST to /pools with the payload:
```json
{
    "name": "ACME_COIN",
    "symbol": "$ACME",
    "type":"fungible",
    "connector": "erc1155"
}
```

The transaction succeeds, but no token pool gets created:
![image](https://user-images.githubusercontent.com/17093033/163626772-df1ad862-0054-46ac-b9ef-85643c32d53e.png)

I reproduced this in a single connector environment with erc1155 and the token pool is created as expected.

Logs:
[poolBug.log](https://github.com/hyperledger/firefly/files/8498048/poolBug.log)

**Comment by awrichar** [comment]
Was not able to reproduce on latest mainline. @eberger727 can you confirm?

**Comment by awrichar** [comment]
<img width="1732" alt="Notification_Center" src="https://user-images.githubusercontent.com/1993829/165326727-1ca90d39-01da-43d2-b9f6-7e2898f292e5.png">

**Comment by eberger727** [comment]
I did not have the latest token connector images. There is no bug.
