### ISSUE TITLE
Missing message_id in contractapis

### ISSUE THREAD

**Issue by mfolnovic** [hyperledger/firefly#773]
Hello,

I'm running Firefly v1.0.0-rc.5 under PostgreSQL.

While creating API, I get an error in logs:

`[2022-04-27T13:29:17.185Z] ERROR: SQL query failed: pq: column "message_id" does not exist sql=[ SELECT id, interface_id, location, name, namespace, message_id FROM contractapis WHERE (namespace = $1 AND name = $2) ] dbtx=D_Ys4hok httpreq=6D4zMeUK req=8_Wrk2Xg`

It seems there's a small difference between SQLite and PostgreSQL migrations, where SQLite's migrations have column message_id while PostgreSQL's migrations don't:

https://github.com/hyperledger/firefly/blob/main/db/migrations/sqlite/000052_create_contractapis_table.up.sql
https://github.com/hyperledger/firefly/blob/main/db/migrations/postgres/000052_create_contractapis_table.up.sql

**Comment by nguyer** [comment]
@mfolnovic Thanks for reporting this. This issue has been fixed in https://github.com/hyperledger/firefly/pull/774
