### ISSUE TITLE
Getting Started documentation has many deadlinks to a "keyconcepts" subfolder. 

### ISSUE THREAD

**Issue by bobblessinghartley** [hyperledger/firefly#806]
For example,
https://hyperledger.github.io/firefly/tutorials/events.html#additional-info has a link to https://hyperledger.github.io/firefly/keyconcepts/multiparty_process_flow.html
If the directory was renamed, the links should be updated. If the additional information has been removed, the links should be removed.

**Comment by shorsher** [comment]
I believe this has been fixed in the latest version of the docs, thanks @bobblessinghartley!
