### ISSUE TITLE
TODO: Blob storage/attachment/transfer architecture

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#83]
*** Needs diagram ***

See discussion in: https://github.com/hyperledger-labs/firefly-dataexchange-https/issues/22
See engineering in: https://github.com/hyperledger-labs/firefly/pull/80

**Comment by shorsher** [comment]
https://hyperledger.github.io/firefly/tutorials/broadcast_data.html#example-3-upload-a-blob-with-metadata-and-broadcast
