### ISSUE TITLE
FIR-12: orchestrator per namespace

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly#847]
So far in the implementation of [FIR-12](https://github.com/hyperledger/firefly-fir/pull/12), we have tried to avoid creating multiple instances of managers/plugins/etc. unless absolutely required. After some discussion with @peterbroadhurst, @awrichar and I are going to investigate introducing a `orchestrator` per `namespace`. The main catalyst for this change is HA firefly.

What the world would potentially look like:
* One `orchestrator` per `namespace`
* `NamespaceManager` handles parsing config and instantiating orchestrators
* A global function to get orchestrators by `namespace`
* Each `orchestrator` contains:
  * Singletons for each manager (broadcast, assets, batch, etc.)
  * The configured plugins for the orchestrator's `namespace`

**Comment by awrichar** [comment]
#855
