### ISSUE TITLE
Error occured when I use "ff start <stack>" to start my first stack

### ISSUE THREAD

**Issue by 2590438469** [hyperledger/firefly#907]
Error: docker-compose up -d [1] Creating network "demodev_default" with the default driver
Creating volume "demodev_ethconnect_abis_0" with default driver
Creating volume "demodev_ethconnect_abis_1" with default driver
Creating volume "demodev_ethconnect_events_0" with default driver
Creating volume "demodev_ethconnect_events_1" with default driver
Creating volume "demodev_firefly_core_1" with default driver
Creating volume "demodev_ipfs_data_0" with default driver
Creating volume "demodev_ipfs_data_1" with default driver
Creating volume "demodev_ipfs_staging_0" with default driver
Creating volume "demodev_ipfs_staging_1" with default driver
Pulling firefly_core_1 (hyperledger/firefly:)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

pull access denied for hyperledger/firefly, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

here is the problem ，is that the network problem

**Comment by nguyer** [comment]
Hi @2590438469. Can you please share the following to help narrow down the issue:

1. The version of the FireFly you are running. You can check this by running `ff version`
2. The full `ff init ...` command that you used to create the stack

Thanks!

**Comment by 2590438469** [comment]
> Hi @2590438469. Can you please share the following to help narrow down the issue:
> 
>     1. The version of the FireFly you are running. You can check this by running `ff version`
> 
>     2. The full `ff init ...` command that you used to create the stack
> 
> 
> Thanks!
thank you,

my ff version:
{
  "Version": "1.0.2",
  "Commit": "b5238922bd20368a12a53e82dd84a9cee0c28ab0",
  "Date": "2022-05-18T18:17:17Z",
  "License": "Apache-2.0"
}

and my init command is : ff init dev --external 1

**Comment by awrichar** [comment]
This seems like a network problem. I know there have been issues with fetching containers from GitHub in certain geographies. It does not sound like it's particular to FireFly, but please feel free to reach out on Discord for additional troubleshooting.
