### ISSUE TITLE
Track viper release 1.13

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly#931]
With https://github.com/hyperledger/firefly/pull/930 being merged, we are now pinned to a specific version of viper. Once 1.13 is released, we should track upstream again since it will contain @awrichar's fix.

**Comment by awrichar** [comment]
[It's here](https://github.com/spf13/viper/releases/tag/v1.13.0) 🐍

**Comment by shorsher** [comment]
Merged in https://github.com/hyperledger/firefly/pull/1089/files 🎉 🐍
